image: node:lts
before_script:
  - npm ci
pages:
  script:
    - npm run build
    - rm -rf public
    - mv out public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
